### ISSUE TITLE
Sphinx 2.0 does not work with mscgen

### ISSUE THREAD

**Issue by obonaventure** [sphinx-contrib/mscgen#4]
Hello,

sphinx 2.0 complains when trying to use mscgen 👎 

Running Sphinx v2.0.0
WARNING: while setting up extension sphinxcontrib.mscgen: extension 'sphinxcontrib.mscgen' has no setup() function; is it really a Sphinx extension module?

**Comment by llucax** [comment]
Hi @obonaventure, sadly this project is sort of abandoned, although @carlescufi said he might have some time to dedicate to it, so he is becoming a brand new maintainer :)

I'm not sure what are his plans and needs, but at least there is a bit of light at the end of the tunnel :sparkles:

**Comment by carlescufi** [comment]
@obonaventure I will take a look at this during our own transition to Sphinx 2.0.

**Comment by carlescufi** [comment]
> Hello,
> 
> sphinx 2.0 complains when trying to use mscgen 👎
> 
> Running Sphinx v2.0.0
> WARNING: while setting up extension sphinxcontrib.mscgen: extension 'sphinxcontrib.mscgen' has no setup() function; is it really a Sphinx extension module?

@obonaventure
I cannot reproduce this with Sphinx 2.2.0. The extension seems to work correctly. Can you please let me know how to reproduce this?
EDIT: Also the error message doesn't really make much sense since the extension does have a `setup` method:
https://github.com/sphinx-contrib/mscgen/blob/master/sphinxcontrib/mscgen.py#L212

**Comment by obonaventure** [comment]
This is now solvedn thanks
